PDDL/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from PandDDL import views

urlpatterns = [
    url(r'^siteadmin/', admin.site.urls),
    url(r'^', include('PandDDL.urls'), name="index"),
]

handler403 = views.handler403
handler500 = views.handler500
handler404 = views.handler404

PandDDL/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

app_name = 'PandDDL'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', views.authlogin, name='login'),
    url(r'^changepassword/(?P<uid>[0-9]+)/$', views.changePassword, name='changePassword'),
    url(r'^logout/$', views.authlogout, name='logout'),
    url(r'^rules/$', views.rules, name='rules'),
    url(r'^admin/$', views.adminPage, name='adminPage'),
    url(r'^admin/league/$', views.AdminLeague, name='adminLeague'),
    url(r'^admin/league/setactivelg/(?P<lg_id>[0-9]+)/$', views.setActiveLeague, name='setActiveLeague'),
    url(r'^admin/league/delete/(?P<lge_id>[0-9]+)/$', views.LeagueDelete, name='LeagueDelete'),
    url(r'^admin/league/finishseason/(?P<lge_id>[0-9]+)/$', views.FinishSeason, name='FinishSeason'),
    url(r'^admin/division/$', views.AdminDivision, name='adminDivision'),
    url(r'^admin/division/delete/(?P<div_id>[0-9]+)/$', views.AdminDivisionDelete, name='adminDivisionDelete'),
    url(r'^admin/team/$', views.AdminTeam, name='adminTeam'),
    url(r'^admin/team/pay/(?P<tid>[0-9]+)/$', views.AdminTeamPayLeagueFee, name='adminTeamLeagueFee'),
    url(r'^admin/team/delete/(?P<tid>[0-9]+)/$', views.AdminTeamDelete, name='adminTeamDelete'),
    url(r'^admin/team/points_deduction/delete/(?P<pd_id>[0-9]+)/$', views.AdminTeamPointsDeductionDelete, name='adminTeamDeductionDelete'),
    url(r'^admin/team/password_change/(?P<uid>[0-9]+)/$', views.AdminTeamPasswordChange, name='adminTeamPasswordChange'),
    url(r'^admin/player/$', views.AdminPlayer, name='adminPlayer'),
    url(r'^admin/player/team_select/$', views.AdminPlayerSelectTeam, name='adminPlayerSelectTeam'),
    url(r'^admin/player/captain/(?P<pid>[0-9]+)/$', views.AdminPlayerSetCaptain, name='adminPlayerSetCaptain'),
    url(r'^admin/player/delete/(?P<pid>[0-9]+)/$', views.AdminPlayerDelete, name='adminPlayerDelete'),
    url(r'^admin/fixture/$', views.AdminFixture, name='adminFixture'),
    url(r'^admin/fixture/upload/$', views.fixtureUpload, name='fixtureUpload'),
    url(r'^admin/fixture/generate/$', views.fixtureListGenerate, name='fixtureListGenerate'),
    url(r'^admin/fixture/delete/(?P<fid>[0-9]+)/$', views.AdminFixtureDelete, name='adminFixtureDelete'),
    url(r'^admin/fixture/edit/(?P<fid>[0-9]+)/$', views.AdminFixtureEdit, name='adminFixtureEdit'),
    url(r'^admin/KeyDates/$', views.AdminKeyDates, name='adminKeyDates'),
    url(r'^admin/KeyDates/delete/(?P<kid>[0-9]+)/$', views.AdminKeyDateDelete, name='adminKeyDateDelete'),
    url(r'^admin/announcements/$', views.AdminAnnouncements, name='adminAnnouncements'),
    url(r'^admin/announcements/show/(?P<aid>[0-9]+)/$', views.AdminAnnouncementDisplay, name='adminAnnouncementShow'),
    url(r'^admin/announcements/hide/(?P<aid>[0-9]+)/$', views.AdminAnnouncementHide, name='adminAnnouncementHide'),
    url(r'^admin/announcements/delete/(?P<aid>[0-9]+)/$', views.AdminAnnouncementDelete, name='adminAnnouncementDelete'),
    url(r'^admin/cupcomps/$', views.AdminCupComps, name='adminCupComps'),
    url(r'^admin/playercomps/$', views.AdminPlayerComps, name='adminPlayerComps'),
    url(r'^admin/playercomps/delete/(?P<cid>[0-9]+)/$', views.AdminPlayerCompsDelete, name='adminPlayerCompDelete'),
    url(r'^admin/photo_galleries/$', views.AdminPhotoGalleries, name='adminPhotoGalleries'),
    url(r'^admin/photo_galleries/delete/(?P<pid>[0-9]+)/$', views.AdminPhotoGalleriesDelete, name='adminPhotoGalleriesDelete'),
    url(r'^admin/AGM/$', views.AdminAGMminutes, name='adminAGMminutes'),
    url(r'^galleries/$', views.photoGalleries, name="photoGalleries"),
    url(r'^galleries/(?P<gid>[0-9]+)/$', views.gallery, name="gallery"),
    url(r'^archive/$', views.archive, name="archive"),
    url(r'^AGM/$', views.AGMminutesList, name="AGMminutesList"),
    url(r'^AGM/(?P<path>.*)/$', views.AGMMinutesDownload, name="fileDownload"),
    url(r'^admin/file/delete/(?P<fid>[0-9]+)', views.FileDelete, name="FileDelete"),
    url(r'^admin/AGM/delete/(?P<aid>[0-9]+)/$', views.AdminAGMminutesDelete, name="AGMminutesDelete"),
    url(r'^fixtures/print/(?P<lge_gender>[A-Za-z0-9\']+)_(?P<lge_season>[A-Za-z0-9]+)_(?P<lge_year>[0-9]+)/div(?P<div_id>[A-Za-z0-9]+)/$', views.printFixtures, name='printFixtures'),
    url(r'^fixtures/print/(?P<team_id>[0-9]+)/$', views.printTeamFixtures, name='printTeamFixtures'),
    url(r'^(?P<lge_gender>[A-Za-z0-9\']+)_(?P<lge_season>[A-Za-z0-9]+)_(?P<lge_year>[0-9]+)/$', views.league, name='league'),
    url(r'^(?P<lge_gender>[A-Za-z0-9\']+)_(?P<lge_season>[A-Za-z0-9]+)_(?P<lge_year>[0-9]+)/div(?P<div_id>[A-Za-z0-9]+)/$', views.division, name='division'),
    url(r'^fixture/(?P<fix_id>[0-9]+)/$', views.fixture, name='fixture'),
    url(r'^team/(?P<tid>[0-9\']+)/$',views.team, name='team'),
    url(r'^contact/$',views.contactUs, name='contactUs'),
    url(r'^reportproblem/$', views.reportProblem, name='reportProblem'),
    url(r'^competitions/$', views.CompetitionPage, name='competitions'),
    url(r'^admin/completeissue/(?P<pid>[0-9]+)/$', views.completeIssue, name='completeIssue'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PandDDL/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
import os
import re
from django.conf import settings
import pandas
import xlrd
import math
import datetime
import logging
from django.core.exceptions import PermissionDenied
from django.utils import timezone
from django.shortcuts import render, redirect, render_to_response
from django.template import RequestContext
from django.db.models import Q, Count, Sum
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, JsonResponse, Http404
from operator import itemgetter 
from .models import *
from django.http.response import JsonResponse


# Create your views here.

logger = logging.getLogger(__name__)

def handler403(request, *args, **argv):
    return render(request, 'PandDDL/403.html', status=403)

def handler404(request, *args, **argv):
    return render(request, 'PandDDL/404.html', status=404)

def handler500(request, *args, **argv):
    return render(request, 'PandDDL/500.html', status=500)

def home(request):
    leaguegrps = LeagueGrp.objects.filter(active=True)
    mens_divs = Division.objects.filter(leaguegrp__in=leaguegrps, leaguegrp__gender='Men\'s').order_by('name')
    ladies_divs = Division.objects.filter(leaguegrp__in=leaguegrps, leaguegrp__gender='Ladies').order_by('name')
    noofannouncements = NoOfAnnouncements.objects.get(pk=1)
    announcements = Announcement.objects.filter(showonhome=True).order_by('-date')[:noofannouncements.number]
    galleries = PhotoGallery.objects.all()
    
    context = {
        "leaguegrps": leaguegrps,
        "announcements": announcements,
        "galleries": galleries,
        "mens_divs": mens_divs,
        "ladies_divs": ladies_divs,
    }
    
    return render(request, 'PandDDL/home.html', context)

def contactUs(request):
    context = {}
    
    return render(request, 'PandDDL/contact.html', context)

def reportProblem(request):
    report_success = False
    if 'problem_reported' in request.session:
        if request.session['problem_reported']:
            report_success = True
    
    try:
        del request.session['problem_reported']
    except:
        pass
    
    if request.method == "POST":
        problemdesc = request.POST.get('problem-description')
        reporter = request.POST.get('reporter-email')
        newproblem = Problem(date_reported=datetime.datetime.now(), reporter_email=reporter, problem_desc=problemdesc, completed=False)
        newproblem.save()
        request.session['problem_reported'] = True
        
        return redirect('PandDDL:reportProblem')
        
    
    context = {
        "report_success": report_success,
    }
    
    return render(request, 'PandDDL/reportproblem.html', context)

def completeIssue(request, pid):
    issue = Problem.objects.get(pk=pid)
    issue.completed=True
    issue.save()
    return redirect('PandDDL:adminPage')

def authlogin(request):
    
    if request.method == "POST":
        active_leagues = LeagueGrp.objects.filter(active=True).order_by('-gender')
        postusername = request.POST.get('username')
        postpassword = request.POST.get('password')
        user = authenticate(username=postusername, password=postpassword)
        if user is not None:
            # A backend authenticated the credentials
            login(request, user)
            if not user.is_staff:
                user_team = Team.objects.get(admin__pk=user.pk, division__leaguegrp__in=active_leagues)
                if user_team.newpassword:
                    return redirect('PandDDL:changePassword', user.pk)
            return redirect('PandDDL:home')
        else:
            # No backend authenticated the credentials
            return redirect('PandDDL:login')
    
    context = {
    
    }
    
    return render(request, 'PandDDL/login.html', context)

def changePassword(request, uid):
    user_test = User.objects.get(pk=uid)
    if request.user != user_test:
        raise PermissionDenied
    if request.method == "POST":
        user = authenticate(username=user_test.username, password=request.POST.get('old-password'))
        if user is not None and request.POST.get('change-password') and request.POST.get('change-password') == request.POST.get('change-password-confirm'):
            user.set_password(request.POST.get('change-password'))
            team = Team.objects.get(admin=user, division__leaguegrp__active=True)
            team.newpassword = False
            team.save()
            user.save()
            login(request, user)
            return redirect('PandDDL:home')
        else: 
            return redirect('PandDDL:changePassword', user.pk)
    
    context = {
    
    }
    
    return render(request, 'PandDDL/changePassword.html', context)

def authlogout(request):
    logout(request)
    
    return redirect('PandDDL:home')

def league(request, lge_gender, lge_season, lge_year):
    lge = LeagueGrp.objects.get(gender=lge_gender, season=lge_season, year=lge_year)
    divs = Division.objects.filter(leaguegrp=lge.pk)
    cups = CupComp.objects.filter(leaguegrp=lge.pk)
    
    context = {
        "league": lge,
        "divs": divs,
        "cups": cups,
    }
            
    return render(request, 'PandDDL/league.html', context)

def CompetitionPage(request):
    results = Competition.objects.filter(keydate__league__active=True).exclude(winner1=None).order_by('keydate__date')
    fixtures = Competition.objects.filter(keydate__league__active=True, winner1=None).order_by('keydate__date')
    
    context = {
        "cup_results": results,
        "cup_fixtures": fixtures,
    }
    
    return render(request, 'PandDDL/cup.html', context)

def division(request, lge_gender, lge_season, lge_year, div_id):
    lge = LeagueGrp.objects.get(gender=lge_gender, season=lge_season, year=lge_year)
    div = Division.objects.get(leaguegrp=lge.pk, name=div_id)
    div_teams = Team.objects.filter(division=div.pk)
    points_deductions = PointsDeduction.objects.filter(team__in=div_teams).order_by('date', 'team__name')
    no_of_teams_form = 5
    points_deductions_teams = []
    for d in points_deductions:
        points_deductions_teams.append(d.team.name)
    div_table = Result.objects.filter(team__division=div.pk, fixture__resultverified=True).values('team__name', 'team__id').annotate(Cplayed=Sum('played'), Cwon=Sum('win'), Clost=Sum('lose'), Clegs_for=Sum('legs_for'), Clegs_ags=Sum('legs_against'), Cpoints=Sum('points')).order_by('-Cpoints', '-Clegs_for', 'Clegs_ags', 'team__name')
    div_table_f = []
    for team in div_teams:
        try:
            table_team = div_table.get(team=team)
        except Result.DoesNotExist:
            table_team = None
        points_deducted = 0
        for d in points_deductions:
            if team == d.team:
                points_deducted += d.points
        if table_team != None:
            teamresults = Result.objects.filter(team=team, fixture__resultverified=True).order_by('-fixture__date')[:no_of_teams_form][::-1]
            teamobj = {"teamName": table_team['team__name'], "teamid": table_team['team__id'], "Cplayed": table_team['Cplayed'], "Cwon": table_team['Cwon'], "Clost": table_team['Clost'], "Clegs_for": table_team['Clegs_for'], "Clegs_ags": table_team['Clegs_ags'], "Cpoints": table_team['Cpoints']-points_deducted, "results": teamresults}
        else:
            teamobj = {"teamName": team.name, "teamid": team.id, "division": team.division, "Cplayed": 0, "Cwon": 0, "Clost": 0, "Clegs_for": 0, "Clegs_ags": 0, "Cpoints": 0-points_deducted}
        div_table_f.append(teamobj)
        div_table_f = sorted(div_table_f, key=itemgetter('Clegs_ags', 'teamName'))
        div_table_f = sorted(div_table_f, key=itemgetter('Cpoints', 'Clegs_for'), reverse=True)
        
    div_players = Player.objects.filter(team__in=div_teams)
    maximum_table= Maximum.objects.filter(player__team__division=div.pk, fixture__resultverified=True).values('player', 'player__firstname', 'player__surname', 'player__team__name').annotate(Count("id")).order_by('-id__count', 'player__surname')
    finishes_table = TopFinish.objects.filter(player__in=div_players, fixture__resultverified=True).order_by('-finish', 'fixture__date')
    scores_table = TopScore.objects.filter(player__in=div_players, fixture__resultverified=True).values('player', 'player__firstname', 'player__surname', 'player__team__name').annotate(Sum("score")).order_by('-score__sum', 'player__surname')
    fixture_dates = Fixture.objects.filter(division=div).values('date').order_by('date').distinct()
    fixtures = Fixture.objects.filter(hometeam__in=div_teams).order_by('date')
    teams_with_bye = []
    for d in fixture_dates:
        fixtures_on_date = fixtures.filter(date=d['date'])
        teams_on_date = []
        for fixture in fixtures_on_date:
            teams_on_date.append(fixture.hometeam)
            teams_on_date.append(fixture.awayteam)
        for team in div_teams:
            if not team in teams_on_date:
                teams_with_bye.append({"date":d['date'], "team":team})
    top_singles_table = SinglesResult.objects.filter(player__team__in=div_teams, match__fixture__resultverified=True).values('player', 'player__firstname', 'player__surname', 'player__team__name').annotate(Cplayed=Sum('played'), Cwon=Sum('win'), Clost=Sum('lose'), Clegs_for=Sum('legs_for'), Clegs_ags=Sum('legs_against')).order_by('-Cwon', '-Clegs_for', 'Clegs_ags', 'player__surname')
    top_singles_table = top_singles_table.filter(Cwon__gt=0)[:10]

PandDDL/templates/PandDDL/adminPage.html
{% extends "./base.html" %}
{% load static %}
{% block content %}
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item active" aria-current="page">Admin Home</li>
		<li class="breadcrumb-item"><a href="{% url 'PandDDL:adminLeague' %}">League</a></li>
		<li class="breadcrumb-item"><a href="{% url 'PandDDL:adminDivision' %}">Division</a></li>
		<li class="breadcrumb-item"><a href="{% url 'PandDDL:adminFixture' %}">Fixture</a></li>
		<li class="breadcrumb-item"><a href="{% url 'PandDDL:adminTeam' %}">Team</a></li>
		<li class="breadcrumb-item"><a href="{% url 'PandDDL:adminPlayer' %}">Player</a></li>
		<li class="breadcrumb-item"><a href="{% url 'PandDDL:adminPlayerComps' %}">Player Competitions</a></li>
		<li class="breadcrumb-item"><a href="{% url 'PandDDL:adminKeyDates' %}">Key Dates</a></li>
		<li class="breadcrumb-item"><a href="{% url 'PandDDL:adminAnnouncements' %}">Announcements</a></li>
		<li class="breadcrumb-item"><a href="{% url 'PandDDL:adminPhotoGalleries' %}">Photo Galleries</a></li>
		<li class="breadcrumb-item"><a href="{% url 'PandDDL:adminAGMminutes' %}">AGM Minutes & Files</a></li>
	</ol>
</nav>

<h1>Admin Tools</h1>

<h3>Issues Reported</h3>
{% if reported_problems|length == 0 %}
<p>No Issues Reported By Users</p>
{% else %}
<table class="table">
	<tr>
		<th>Reported On</th>
		<th>Reported By</th>
		<th>Issue Description</th>
		<th></th>
	</tr>
	{% for issue in reported_problems %}
	<tr>
		<td>{{ issue.date_reported }}</td>
		<td>{% if issue.reporter_email %}{{ issue.reporter_email }}{% else %}Anonymous{% endif %}</td>
		<td>{{ issue.problem_desc|linebreaks }}</td>
		<td><a href="{% url 'PandDDL:completeIssue' issue.pk %}">Complete</a></td>
	{% endfor %}
</table>
{% endif %}

<div class="row">
	<div class="col-md-6">
		<h3>Results Not Entered</h3>
		<ul class="nav nav-tabs">
		  <li class="active"><a data-toggle="tab" href="#mensLeagueentered">Men's Divisions ({{ mens_results_not_entered|length }})</a></li>
		  <li><a data-toggle="tab" href="#ladiesLeagueentered">Ladies' Divisions ({{ ladies_results_not_entered|length }})</a></li>
		</ul>
		
		<div class="tab-content">
			<div id="mensLeagueentered" class="tab-pane fade in active">
				{% if mens_results_not_entered|length == 0 %}
				<p>All results entered</p>
				{% else %}
				<table class="table">
					{% for fixture in mens_results_not_entered %}
					<tr>
						<td><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;">{{ fixture.date }}</a></td>
						<td style="width:35%;"><a href="{% url 'PandDDL:fixture' fixture.pk %}">{{ fixture.hometeam.name }}</a></td>
						<td><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;text-align:center;">-</a></td>
						<td style="width:35%;"><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;text-align:right;">{{ fixture.awayteam.name }}</a></td>
					</tr>
					{% endfor %}
				</table>
				{% endif %}
			</div>
			<div id="ladiesLeagueentered" class="tab-pane fade in">
				{% if ladies_results_not_entered|length == 0 %}
				<p>All results entered</p>
				{% else %}
				<table class="table">
					{% for fixture in ladies_results_not_entered %}
					<tr>
						<td><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;">{{ fixture.date }}</a></td>
						<td style="width:35%;"><a href="{% url 'PandDDL:fixture' fixture.pk %}">{{ fixture.hometeam.name }}</a></td>
						<td><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;text-align:center;">-</a></td>
						<td style="width:35%;"><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;text-align:right;">{{ fixture.awayteam.name }}</a></td>
					</tr>
					{% endfor %}
				</table>
				{% endif %}
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<h3>Results Not Verified</h3>
		<ul class="nav nav-tabs">
		  <li class="active"><a data-toggle="tab" href="#mensLeague">Men's Divisions ({{ mens_results_not_verified|length }})</a></li>
		  <li><a data-toggle="tab" href="#ladiesLeague">Ladies' Divisions ({{ ladies_results_not_verified|length }})</a></li>
		</ul>
		
		<div class="tab-content">
			<div id="mensLeague" class="tab-pane fade in active">
				{% if mens_results_not_verified|length == 0 %}
				<p>All results verified</p>
				{% else %}
				<table class="table">
					{% for fixture in mens_results_not_verified %}
					<tr>
						<td><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;">{{ fixture.date }}</a></td>
						<td style="width:30%;"><a href="{% url 'PandDDL:fixture' fixture.pk %}">{{ fixture.hometeam.name }}</a></td>
						<td><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;text-align:center;">{{ fixture.homescore }}</a></td>
						<td><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;text-align:center;">-</a></td>
						<td><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;text-align:center;">{{ fixture.awayscore }}</a></td>
						<td style="width:30%;"><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;text-align:right;">{{ fixture.awayteam.name }}</a></td>
					</tr>
					{% endfor %}
				</table>
				{% endif %}
			</div>
			<div id="ladiesLeague" class="tab-pane fade in">
				{% if ladies_results_not_verified|length == 0 %}
				<p>All results verified</p>
				{% else %}
				<table class="table">
					{% for fixture in ladies_results_not_verified %}
					<tr>
						<td><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;">{{ fixture.date }}</a></td>
						<td style="width:30%;"><a href="{% url 'PandDDL:fixture' fixture.pk %}">{{ fixture.hometeam.name }}</a></td>
						<td><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;text-align:center;">{{ fixture.homescore }}</a></td>
						<td><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;text-align:center;">-</a></td>
						<td><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;text-align:center;">{{ fixture.awayscore }}</a></td>
						<td style="width:30%;"><a href="{% url 'PandDDL:fixture' fixture.pk %}" style="display:block;text-align:right;">{{ fixture.awayteam.name }}</a></td>
					</tr>
					{% endfor %}
				</table>
				{% endif %}
			</div>
	</div>
</div>


{% endblock %}

PandDDL/templates/PandDDL/cup.html
{% extends "./base.html" %}
{% load static %}
{% block content %}

<h1>Competitions</h1>
<h3>Results</h3>

<table class="table">
	<tr>
		<th>Date</th>
		<th>Competition</th>
		<th>Winner(s)</th>
		<th>Runner-Up(s)</th>
	</tr>
{% for result in cup_results %}
	<tr>
		<td>{{ result.keydate.date }}</td>
		<td>{{ result.keydate.name }}</td>
		<td>
			{% if result.winner1 %}{{ result.winner1.firstname }}{{ result.winner1.surname }}{% endif %}
			{% if result.winner2 %}<br>{{ result.winner2.firstname }}{{ result.winner2.surname }}{% endif %}
			{% if result.winner3 %}<br>{{ result.winner3.firstname }}{{ result.winner3.surname }}{% endif %}
		</td>
		<td>
			{% if result.runnerup1 %}{{ result.runnerup1.firstname }}{{ result.runnerup1.surname }}{% endif %}
			{% if result.runnerup2 %}<br>{{ result.runnerup2.firstname }}{{ result.runnerup2.surname }}{% endif %}
			{% if result.runnerup3 %}<br>{{ result.runnerup3.firstname }}{{ result.runnerup3.surname }}{% endif %}
		</td>
	</tr>
{% endfor %}
</table>


<h3>Upcoming</h3>

<table class="table">
	<tr>
		<th>Date</th>
		<th>Time</th>
		<th>Location</th>
		<th>Competition</th>
		<th>Type</th>
	</tr>
{% for fixture in cup_fixtures %}
	<tr>
		<td>{{ fixture.keydate.date }}</td>
		<td>{{ fixture.keydate.time }}</td>
		<td>{{ fixture.keydate.location }}</td>
		<td>{{ fixture.keydate.name }}</td>
		<td>{{ fixture.comptype }}</td>
	</tr>
{% endfor %}
</table>
{% endblock %}

PandDDL/templates/PandDDL/photoGallery.html
{% extends "./base.html" %}
{% load static %}
{% block content %}

<h1>{{ gallery.name }}<span class="back-page-link"><a href="{% url 'PandDDL:photoGalleries' %}">Back to Galleries</a></span></h1>
<h4>{{ gallery.date }}</h4>

{% if gallery.photos.all|length != 0 %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
    	{% for p in gallery.photos.all %}
	    <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}" {% if forloop.counter0 == 0 %}class="active"{% endif %}></li>
	    {% endfor %}
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
    	{% for p in gallery.photos.all %}
	    <div class="item {% if forloop.counter0 == 0 %}active{% endif %}">
	     	<img src="{{ p.photo.url }}" alt="{{ gallery.name }}_{{ forloop.counter }}" style="width:100%; height:600px; object-fit:contain;">
	    </div>
		{% endfor %}

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
</div>
{% endif %}

{% endblock %}